version: '3.9'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - 80:80

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 4000:4000
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD: 123456
      - POSTGRES_USER: postgre-db
    ports:
      - 5432:5432
